### ISSUE TITLE
Add the file command to the base container

### ISSUE THREAD

**Issue by Mankro** [apluslms/grading-base#4]
The standard UNIX `file` command is used to check the file type of a file. A teacher requested that this command should be included in grading containers.

**Comment by raphendyr** [comment]
> A teacher requested that this command should be included in grading containers.

I think these kind of statements should always include the use case. Often, people request the thing that solves an issue for them, but the solution isn't actually a good one, it's just the one they came up with. Thus, knowing the issue, we can reevaluate, if the solution fits the usecase.

That said, for the purpose of validating that the file is a type of X, we should do that in the grader at the latest. Related issues https://github.com/apluslms/mooc-grader/issues/52

In any case, we can easily include `file` as it's super small binary. Though, it has a small possibility to promote testing files in a wrong place, but I don't worry about it too much.

**Comment by Mankro** [comment]
More teachers have requested the file command. It seems that people find it useful. We have no reason not to install it so we shall do it.

**Comment by raphendyr** [comment]
> More teachers have requested the file command. It seems that people find it useful. We have no reason not to install it so we shall do it.

Sure. Any case, I would be interested for usecases, so they are documented somewhere and thus can be used for future development.

**Comment by Mankro** [comment]
At least one usecase now was that the teachers want to check the type of submitted files in manually graded exercises. Even though the exercise is manually graded, the teachers want to give automatic feedback to the students if they submit files of the wrong type. The feedback also reveals it immediately to the assistants if the file has the wrong type.

**Comment by jaguarfi** [comment]
Is this related [#52](https://github.com/apluslms/mooc-grader/issues/52) ?

**Comment by Mankro** [comment]
Like raphendyr said earlier, https://github.com/apluslms/mooc-grader/issues/52 is related in the sense that the submission file type should be checked before the submission is graded in a container. The submission could be rejected much earlier based on the wrong file type. Frontend JavaScript in A+ could check it before the user has even submitted the file to the server and the A+ server could reject wrong file types before sending the submission to the grader.

**Comment by Mankro** [comment]
I added the file command in the commit https://github.com/apluslms/grading-base/commit/b88b8d43e55cd629bafe3192f55e81311dbc2da8, but the question of releasing the container with a new version number remains. I think someone wanted the file command in the grade-python container, so that needs to be updated too.

**Comment by Mankro** [comment]
The released container `apluslms/grading-base:3.1` includes this update now.
